name: Pull Request or push
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install web dependencies
        run: npm i
      - name: Package
        run: npm run package
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: plugin.zip
          asset_name: plugin
          tag: ${{ github.ref }}
          overwrite: true